### ISSUE TITLE
Fix issue with "change network to polygon" on `game-redo` branch

### ISSUE THREAD

**Issue by Gizmotronn** [Signal-K/polygon#12]
In the branch for #3 we can't log in to the app as we keep getting an error message "Change network to Polygon", where the `ganache-cli` instance is not valid (and neither is the Mumbai testnet or Matic mainnet). After cloning [the base repo](https://github.com/HashLips/nft_game) I found that the desired network is Matic, so we likely need to update this in `src/redux/blockchain`, and configuring the network to work for the ganache network or either of the polygon networks. Gas fees aren't an issue on Matic (mainnet) so it is potentially plausible that it would be fine ignoring Ganache for now...or extending it later.

Just need to compare `src/App.js` and the redux directory...

**Comment by Frankdev012** [comment]
Hello @Gizmotronn  A support ticket has been opened for you. Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into. [CLICK HERE](https://forummaticnetwork.com/)
